/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlahov.client.components;

import com.kvlahov.client.global.Constants;
import com.kvlahov.client.tableModels.StatPatientsTreatedTableModel;
import com.kvlahov.client.tableModels.StatSummaryTableModel;
import com.kvlahov.model.report.DailyReport;
import java.awt.event.ActionListener;

/**
 *
 * @author lordo
 */
public class DailyReportComponent extends javax.swing.JPanel {

    private DailyReport dailyReport;
    private ActionListener btnSaveActionListener;

    public DailyReportComponent(DailyReport dailyReport) {
        this.dailyReport = dailyReport;

        initComponents();
        initUI();

    }

    public DailyReport getDailyReport() {
        return dailyReport;
    }

    public void setDailyReport(DailyReport dailyReport) {
        this.dailyReport = dailyReport;
    }

    public ActionListener getBtnSaveActionListener() {
        return btnSaveActionListener;
    }

    public void setBtnSaveActionListener(ActionListener btnSaveActionListener) {
        this.btnSaveActionListener = btnSaveActionListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        patientsTreatedPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientsTreated = new javax.swing.JTable();
        summaryPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSummary = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNewPatients = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblRecurringPatients = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        mainPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 50));
        mainPane.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Daily Report");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.3;
        mainPane.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        mainPane.add(jLabel2, gridBagConstraints);

        lblDate.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mainPane.add(lblDate, gridBagConstraints);

        patientsTreatedPane.setBorder(new javax.swing.border.MatteBorder(null));
        patientsTreatedPane.setLayout(new java.awt.BorderLayout());

        tblPatientsTreated.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPatientsTreated);

        patientsTreatedPane.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        mainPane.add(patientsTreatedPane, gridBagConstraints);

        summaryPane.setBorder(new javax.swing.border.MatteBorder(null));
        summaryPane.setLayout(new java.awt.BorderLayout());

        tblSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSummary);

        summaryPane.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        mainPane.add(summaryPane, gridBagConstraints);

        jLabel5.setText("Patients treated by doctors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weighty = 0.5;
        mainPane.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Service Summary");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weighty = 0.3;
        mainPane.add(jLabel6, gridBagConstraints);

        jLabel3.setText("Number of new patients:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        mainPane.add(jLabel3, gridBagConstraints);

        lblNewPatients.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mainPane.add(lblNewPatients, gridBagConstraints);

        jLabel7.setText("Number of Recurring patients:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        mainPane.add(jLabel7, gridBagConstraints);

        lblRecurringPatients.setText("jLabel8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mainPane.add(lblRecurringPatients, gridBagConstraints);

        add(mainPane, java.awt.BorderLayout.CENTER);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(btnSaveActionListener != null) {
            btnSaveActionListener.actionPerformed(evt);
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblNewPatients;
    private javax.swing.JLabel lblRecurringPatients;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel patientsTreatedPane;
    private javax.swing.JPanel summaryPane;
    private javax.swing.JTable tblPatientsTreated;
    private javax.swing.JTable tblSummary;
    // End of variables declaration//GEN-END:variables

    private void initUI() {
        initTblPatientsTreated();
        initTblSummary();
        initLabels();
    }

    private void initLabels() {
        lblDate.setText(dailyReport.getDate().format(Constants.DATE_FORMAT));
        lblNewPatients.setText(String.valueOf(dailyReport.getNewReccuringPatients().getNoNewPatients()));
        lblRecurringPatients.setText(String.valueOf(dailyReport.getNewReccuringPatients().getNoRecurringPatients()));
    }

    private void initTblPatientsTreated() {
        tblPatientsTreated.setModel(new StatPatientsTreatedTableModel(dailyReport.getPatientsTreated()));
        tblPatientsTreated.setRowHeight(50);
    }

    private void initTblSummary() {
        tblSummary.setRowHeight(50);
        tblSummary.setModel(new StatSummaryTableModel(dailyReport.getServicesSummary()));
    }
}
