/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlahov.client.components;

import com.kvlahov.model.patientInfo.LifestyleInfo;

/**
 *
 * @author lordo
 */
public class LifeStyleComponent extends javax.swing.JPanel {
    private LifestyleInfo lifestyle = new LifestyleInfo();
    /**
     * Creates new form LifeStyleComponent
     */
    public LifeStyleComponent() {
        initComponents();
    }

    public LifestyleInfo getLifestyle() {
        bindUIToModel();
        return lifestyle;
    }

    public void setLifestyle(LifestyleInfo lifestyle) {
        this.lifestyle = lifestyle;
        updateLifestyleUI();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel39 = new javax.swing.JLabel();
        lblBloodType1 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        tfStimulatns = new javax.swing.JTextField();
        tfEatingHabits = new javax.swing.JTextField();
        spCaffeine = new javax.swing.JSpinner();
        spSoftDrinks = new javax.swing.JSpinner();
        cbVege = new javax.swing.JCheckBox();
        cbSmokes = new javax.swing.JCheckBox();
        cbAlcohol = new javax.swing.JCheckBox();
        spCigarettesPerDay = new javax.swing.JSpinner();
        jLabel45 = new javax.swing.JLabel();
        spAlcoholPerDay = new javax.swing.JSpinner();
        jLabel46 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel39.setText("Uses Stimulants");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(jLabel39, gridBagConstraints);

        lblBloodType1.setText("Consumption of caffeine drinks per day");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(lblBloodType1, gridBagConstraints);

        jLabel40.setText("Consumption of soft drinks per day");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(jLabel40, gridBagConstraints);

        jLabel41.setText("Eating Habits");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(jLabel41, gridBagConstraints);

        tfStimulatns.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        add(tfStimulatns, gridBagConstraints);

        tfEatingHabits.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        add(tfEatingHabits, gridBagConstraints);

        spCaffeine.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        add(spCaffeine, gridBagConstraints);

        spSoftDrinks.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        add(spSoftDrinks, gridBagConstraints);

        cbVege.setText("Vegetarian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(cbVege, gridBagConstraints);

        cbSmokes.setText("Smokes");
        cbSmokes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSmokesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(cbSmokes, gridBagConstraints);

        cbAlcohol.setText("Consumes Alcohol");
        cbAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlcoholActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(cbAlcohol, gridBagConstraints);

        spCigarettesPerDay.setModel(new javax.swing.SpinnerNumberModel());
        spCigarettesPerDay.setEnabled(false);
        spCigarettesPerDay.setName("spinnerCigsPerDay"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        add(spCigarettesPerDay, gridBagConstraints);

        jLabel45.setText("No of cigarettes per day");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(jLabel45, gridBagConstraints);

        spAlcoholPerDay.setModel(new javax.swing.SpinnerNumberModel());
        spAlcoholPerDay.setEnabled(false);
        spAlcoholPerDay.setName("spAlcoholPerDay"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.1;
        add(spAlcoholPerDay, gridBagConstraints);

        jLabel46.setText("No of alcoholic beverages per day");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(jLabel46, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cbSmokesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSmokesActionPerformed
        spCigarettesPerDay.setEnabled(cbSmokes.isEnabled());
        if (cbSmokes.isEnabled() == false) {
            spCigarettesPerDay.setValue(0);
        }
    }//GEN-LAST:event_cbSmokesActionPerformed

    private void cbAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlcoholActionPerformed
        spAlcoholPerDay.setEnabled(cbAlcohol.isEnabled());
        if (cbAlcohol.isEnabled() == false) {
            spAlcoholPerDay.setValue(0);
        }
    }//GEN-LAST:event_cbAlcoholActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAlcohol;
    private javax.swing.JCheckBox cbSmokes;
    private javax.swing.JCheckBox cbVege;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel lblBloodType1;
    private javax.swing.JSpinner spAlcoholPerDay;
    private javax.swing.JSpinner spCaffeine;
    private javax.swing.JSpinner spCigarettesPerDay;
    private javax.swing.JSpinner spSoftDrinks;
    private javax.swing.JTextField tfEatingHabits;
    private javax.swing.JTextField tfStimulatns;
    // End of variables declaration//GEN-END:variables

    private void bindUIToModel() {
        lifestyle.setAverageCigarettesPerDay((int)spCigarettesPerDay.getValue());
        lifestyle.setAverageDrinksPerDay((int)spAlcoholPerDay.getValue());
        lifestyle.setCoffeineDrinkPerDay((int)spCaffeine.getValue());
        lifestyle.setConsumesAlcohol(cbAlcohol.isSelected());
        lifestyle.setEatingHabits(tfEatingHabits.getText().trim());
        lifestyle.setIsSmoker(cbSmokes.isSelected());
        lifestyle.setIsVegetarian(cbVege.isSelected());
        lifestyle.setSoftDrinkPerDay((int)spSoftDrinks.getValue());
        lifestyle.setUsesStimulants(tfStimulatns.getText().trim());
        
    }

    private void updateLifestyleUI() {
        if(lifestyle == null) return;
        tfEatingHabits.setText(lifestyle.getEatingHabits());
        tfStimulatns.setText(lifestyle.getUsesStimulants());
        spAlcoholPerDay.setValue(lifestyle.getAverageDrinksPerDay());
        spCaffeine.setValue(lifestyle.getCoffeineDrinkPerDay());
        spCigarettesPerDay.setValue(lifestyle.getAverageCigarettesPerDay());
        spSoftDrinks.setValue(lifestyle.getSoftDrinkPerDay());
        
        cbAlcohol.setSelected(lifestyle.getConsumesAlcohol());
        cbSmokes.setSelected(lifestyle.getIsSmoker());
        cbVege.setSelected(lifestyle.getIsVegetarian());
    }
}
