/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlahov.client.components;

import com.kvlahov.model.Patient;
import com.kvlahov.model.PaymentMethod;
import com.kvlahov.model.Receipt;
import com.kvlahov.model.ReceiptItem;
import com.kvlahov.model.enums.ComponentMode;
import com.kvlahov.model.patientInfo.ContactInfo;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author lordo
 */
public class ReceiptComponent extends javax.swing.JPanel {
    
    private Receipt receipt;
    private Patient patient;
    private LocalDate appointmentDate;
    
    private List<PaymentMethod> paymentMethods = new ArrayList<>();
    
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private ComponentMode viewMode = ComponentMode.DISPLAY;
    
    public ReceiptComponent(Receipt receipt, Patient patient, LocalDate appointmentDate) {
        this.receipt = receipt;
        this.patient = patient;
        this.appointmentDate = appointmentDate;
        
        initComponents();
        initUI();
        
    }
    
    public Receipt getReceipt() {
        receipt.setPaymentMethod((PaymentMethod) ddlPaymentMethod.getSelectedItem());
        return receipt;
    }
    
    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }
    
    public Patient getPatient() {
        return patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    
    public LocalDate getAppointmentDate() {
        return appointmentDate;
    }
    
    public void setAppointmentDate(LocalDate appointmentDate) {
        this.appointmentDate = appointmentDate;
    }
    
    public void setEditMode(List<PaymentMethod> paymentMethods) {
        this.viewMode = ComponentMode.EDIT;
        this.paymentMethods = paymentMethods;
        
        updatePaymentMethodComponent();
    }
    
    public List<PaymentMethod> getPaymentMethods() {
        return paymentMethods;
    }
    
    public void setPaymentMethods(List<PaymentMethod> paymentMethods) {
        this.paymentMethods = paymentMethods;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        receiptPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblReceiptDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAppointmentDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        receiptItemsPane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblReceiptNumber = new javax.swing.JLabel();
        lblPatientInfo = new javax.swing.JLabel();
        paymentPane = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        receiptPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 60, 1, 60));
        receiptPane.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Virgo Hospital United");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        receiptPane.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Receipt NO:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        receiptPane.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        receiptPane.add(jLabel4, gridBagConstraints);

        lblReceiptDate.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        receiptPane.add(lblReceiptDate, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Appointment date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        receiptPane.add(jLabel6, gridBagConstraints);

        lblAppointmentDate.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        receiptPane.add(lblAppointmentDate, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Payment Method");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 10);
        receiptPane.add(jLabel8, gridBagConstraints);

        receiptItemsPane.setBorder(new javax.swing.border.MatteBorder(null));
        receiptItemsPane.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        receiptPane.add(receiptItemsPane, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Total");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        receiptPane.add(jLabel10, gridBagConstraints);

        lblTotal.setText("N/A");
        lblTotal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 0, 0);
        receiptPane.add(lblTotal, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Receipient");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        receiptPane.add(jLabel12, gridBagConstraints);

        lblReceiptNumber.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        receiptPane.add(lblReceiptNumber, gridBagConstraints);

        lblPatientInfo.setText("N/A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        receiptPane.add(lblPatientInfo, gridBagConstraints);

        paymentPane.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        receiptPane.add(paymentPane, gridBagConstraints);

        add(receiptPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAppointmentDate;
    private javax.swing.JLabel lblPatientInfo;
    private javax.swing.JLabel lblReceiptDate;
    private javax.swing.JLabel lblReceiptNumber;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel paymentPane;
    private javax.swing.JPanel receiptItemsPane;
    private javax.swing.JPanel receiptPane;
    // End of variables declaration//GEN-END:variables
    private Component paymentMethodComponent;
    private JComboBox ddlPaymentMethod;
    
    private void initUI() {
        if (patient != null) {
            updatePatientUI(patient);
        }
        
        if (receipt != null) {
            updateReceiptUI(receipt);
        }
        
        List<ReceiptItem> receiptItems = receipt.getItems();
        if (receiptItems != null) {
            updateReceiptItemsUI(receiptItems);
        }
        if (appointmentDate != null) {
            updateAppointmentUI(appointmentDate);
        }
        if (paymentMethods != null) {
            ddlPaymentMethod = new JComboBox(new DefaultComboBoxModel(paymentMethods.toArray()));
            ddlPaymentMethod.setSelectedItem(receipt.getPaymentMethod());
            
            ddlPaymentMethod.addItemListener((e) -> {
                receipt.setPaymentMethod((PaymentMethod) ddlPaymentMethod.getSelectedItem());
            });
        }
    }
    
    private void updatePatientUI(Patient patient) {
        StringBuilder sb = new StringBuilder();
        sb.append(patient.toString());
        
        lblPatientInfo.setText(sb.toString());
        
    }
    
    private void updateReceiptUI(Receipt receipt) {
        lblReceiptNumber.setText(receipt.getReceiptNumber());
        lblReceiptDate.setText(receipt.getDate().format(DATE_FORMAT));
        addPaymentMethod();
        lblTotal.setText(String.valueOf(receipt.getTotal()));
    }
    
    private void updateReceiptItemsUI(List<ReceiptItem> receiptItems) {
        receiptItemsPane.removeAll();
        ReceiptItemListComponent items = new ReceiptItemListComponent();
        items.setReceiptItems(receiptItems);
        
        receiptItemsPane.add(items);
    }
    
    private void updateAppointmentUI(LocalDate appointmentDate) {
        lblAppointmentDate.setText(appointmentDate.format(DATE_FORMAT));
    }
    
    private void addPaymentMethod() {
        paymentMethodComponent = new JLabel("N/A");
        switch (viewMode) {
            case EDIT:
                paymentMethodComponent = ddlPaymentMethod;
                break;
            default:
                if (receipt.getPaymentMethod() != null) {
                    paymentMethodComponent = new JLabel(receipt.getPaymentMethod().toString());
                }
                break;
        }
        
        paymentPane.add(paymentMethodComponent);
    }
    
    private void updatePaymentMethodComponent() {
        switch (viewMode) {
            case EDIT:
                ddlPaymentMethod.setModel(new DefaultComboBoxModel(paymentMethods.toArray()));
                paymentMethodComponent = ddlPaymentMethod;
                break;
            default:
                paymentMethodComponent = new JLabel(receipt.getPaymentMethod().toString());
                break;
        }
        
        paymentPane.removeAll();
        paymentPane.add(paymentMethodComponent);
        
    }
    
}
