/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlahov.client.components;

import com.kvlahov.model.Service;
import com.kvlahov.model.ServiceAppointment;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author lordo
 */
public class ServiceForAppointment extends javax.swing.JPanel {

    /**
     * Creates new form ServiceForAppointment
     */
    private ServiceAppointment service = new ServiceAppointment();
    private String serviceName;
    private List<Service> services = new ArrayList<>();

    private ActionListener btnRemoveActionListener = null;

    public ServiceForAppointment() {
        initComponents();
        updateDetailsPane();
        registerEvents();

    }

    public ServiceForAppointment(ServiceAppointment service, String serviceName) {
        initComponents();
        this.service = service;
        this.serviceName = serviceName;

        updateDetailsPane();
    }

    public ServiceAppointment getService() {
        return service;
    }

    public void setService(ServiceAppointment service) {
        this.service = service;
    }

    public String getServiceName() {
        return serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public void addBtnRemoveActionListener(ActionListener action) {
        this.btnRemoveActionListener = action;
    }

    public void removeBtnRemoveActionListener() {
        this.btnRemoveActionListener = null;
    }

    private final CardLayout cardLayout = new CardLayout();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetails = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        panelEdit = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ddlService = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        spQuantity = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        tfDescription = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelDetails.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Service:");
        panelDetails.add(jLabel8);

        lblService.setText("N/A");
        panelDetails.add(lblService);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Quantity:");
        panelDetails.add(jLabel10);

        lblQuantity.setText("N/A");
        panelDetails.add(lblQuantity);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Description");
        panelDetails.add(jLabel11);

        lblDescription.setText("N/A");
        panelDetails.add(lblDescription);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelDetails.add(btnEdit);

        btnRemove.setText("Remove");
        panelDetails.add(btnRemove);

        add(panelDetails, "card2");

        panelEdit.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Service:");
        panelEdit.add(jLabel6);

        ddlService.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelEdit.add(ddlService);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Quantity:");
        panelEdit.add(jLabel7);

        spQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        panelEdit.add(spQuantity);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Description");
        panelEdit.add(jLabel9);

        tfDescription.setColumns(20);
        panelEdit.add(tfDescription);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelEdit.add(btnSave);

        add(panelEdit, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Object selectedItem = ddlService.getSelectedItem();
        if (selectedItem instanceof Service) {
            service.setServiceId(((Service) selectedItem).getId());
        }
        service.setDescription(tfDescription.getText().trim());
        service.setQuantity((Integer) spQuantity.getValue());

        updateDetailsPane();
        cardLayout.next(this);


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        cardLayout.next(this);
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox ddlService;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblService;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JSpinner spQuantity;
    private javax.swing.JTextField tfDescription;
    // End of variables declaration//GEN-END:variables

    private void updateDetailsPane() {
        if (service == null) {
            return;
        }

        lblService.setText(serviceName);
        lblQuantity.setText(String.valueOf(service.getQuantity()));
        lblDescription.setText(service.getDescription());
    }

    private void updateEditPane() {
        if (services == null) {
            ddlService.setModel(new DefaultComboBoxModel(new Object[]{serviceName}));
        } else {
            ddlService.setModel(new DefaultComboBoxModel(services.toArray()));
        }
        if (service == null) {
            return;
        }

        spQuantity.setValue(service.getQuantity());
        tfDescription.setText(service.getDescription());
    }

    private void registerEvents() {
        btnRemove.addActionListener(btnRemoveActionListener);
    }
}
