/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlahov.client;

import com.kvlahov.controller.DoctorController;
import com.kvlahov.model.Doctor;
import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author lordo
 */
public class ChooseDoctorUI extends javax.swing.JFrame implements Gui {

    /**
     * Creates new form ChooseDoctorUI
     */
    public ChooseDoctorUI() {
        initComponents();
        initButtons();
        initList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        rbGeneral = new javax.swing.JRadioButton();
        rbSpecialist = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        specialistList = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rbGeneral.setText("General physician");
        rbGeneral.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbGeneralItemStateChanged(evt);
            }
        });
        jPanel3.add(rbGeneral);

        rbSpecialist.setText("Specialist");
        rbSpecialist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbSpecialistItemStateChanged(evt);
            }
        });
        jPanel3.add(rbSpecialist);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 50));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        doctorList.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose general physician"));
        doctorList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        doctorList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(doctorList);

        jPanel1.add(jScrollPane1);

        specialistList.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose specialist"));
        specialistList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        specialistList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(specialistList);

        jPanel1.add(jScrollPane2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Log Out");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbGeneralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbGeneralItemStateChanged
        doctorList.setEnabled(rbGeneral.isSelected());
    }//GEN-LAST:event_rbGeneralItemStateChanged

    private void rbSpecialistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbSpecialistItemStateChanged
        specialistList.setEnabled(rbSpecialist.isSelected());
    }//GEN-LAST:event_rbSpecialistItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Doctor selection = null;
        if (rbGeneral.isSelected()) {
            selection = (Doctor) doctorList.getSelectedValue();
        } else if (rbSpecialist.isSelected()) {
            selection = (Doctor) specialistList.getSelectedValue();
        }

        if (selection == null) {
            JOptionPane.showMessageDialog(null, "No doctor selected", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            DoctorUI doctorUi = new DoctorUI(selection);
            doctorUi.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.dispose();
        LoginScreen.start();
    }//GEN-LAST:event_jMenu1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList doctorList;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbGeneral;
    private javax.swing.JRadioButton rbSpecialist;
    private javax.swing.JList specialistList;
    // End of variables declaration//GEN-END:variables
    private ButtonGroup btnGroup;

    private void initList() {
        DefaultListModel generalDoctorModel = new DefaultListModel();
        DefaultListModel specialistModel = new DefaultListModel();
        DoctorController.getAllDoctors().forEach(d -> {
            if (d.getDepartmentID() == 1) {
                generalDoctorModel.addElement(d);
            } else {
                specialistModel.addElement(d);
            }
        });

        doctorList.setModel(generalDoctorModel);
        specialistList.setModel(specialistModel);
    }

    private void initButtons() {
        btnGroup = new ButtonGroup();
        btnGroup.add(rbGeneral);
        btnGroup.add(rbSpecialist);

        rbGeneral.setSelected(true);
        specialistList.setEnabled(false);

    }

    @Override
    public void start() {
        SwingUtilities.invokeLater(() -> {
            ChooseDoctorUI frame = new ChooseDoctorUI();
            frame.setPreferredSize(new Dimension(800, 600));
            frame.setSize(new Dimension(800, 600));
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
}
