/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlahov.client;

import com.kvlahov.client.components.AppointmentsPane;
import com.kvlahov.client.components.CalendarComponent;
import com.kvlahov.client.components.DailyReportComponent;
import com.kvlahov.client.components.GeneralReportComponent;
import com.kvlahov.client.components.GenerateReportComponent;
import com.kvlahov.client.components.NewPatientDialog;
import com.kvlahov.client.components.ReceiptComponent;
import com.kvlahov.client.components.TableComponent;
import com.kvlahov.client.events.TableEvent;
import com.kvlahov.client.events.TableEventListener;
import com.kvlahov.client.tableModels.AppointmentTableModel;
import com.kvlahov.client.tableModels.PatientTableModel;
import com.kvlahov.client.tableModels.ReceiptTableModel;
import com.kvlahov.controller.AppointmentsController;
import com.kvlahov.controller.DoctorController;
import com.kvlahov.controller.PatientController;
import com.kvlahov.controller.ReceiptController;
import com.kvlahov.controller.ReportsController;
import com.kvlahov.exceptions.InvalidModelException;
import com.kvlahov.model.Appointment;
import com.kvlahov.model.Doctor;
import com.kvlahov.model.Patient;
import com.kvlahov.model.Receipt;
import com.kvlahov.model.enums.ReportType;
import com.kvlahov.utils.Utilities;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author lordo
 */
public class RegularUI extends javax.swing.JFrame implements Gui, Observer {

    private List<Patient> patients;
    private List<Doctor> doctors;
    private Patient currentPatient;
    private List<Appointment> scheduledAppointments;

    public RegularUI() {
        initComponents();
        initContent();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        patientListPane = new javax.swing.JPanel();
        patientViewPane = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        personalInfo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        basicInfoPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        patientBasicInfo = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel13 = new javax.swing.JLabel();
        nokBasicInfo = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel15 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel17 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel19 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel21 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        setAppointmentPane = new javax.swing.JPanel();
        finances = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        reportsPane = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miNew = new javax.swing.JMenuItem();
        miShowPatients = new javax.swing.JMenuItem();
        miReports = new javax.swing.JMenu();
        miGenReports = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel9.setText("Home");
        jPanel4.add(jLabel9);

        getContentPane().add(jPanel4, "Home");

        patientListPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(patientListPane, "patientList");

        patientViewPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 10));
        patientViewPane.setLayout(new javax.swing.BoxLayout(patientViewPane, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        personalInfo.setLayout(new javax.swing.BoxLayout(personalInfo, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        basicInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic info"));
        basicInfoPanel.setLayout(new javax.swing.BoxLayout(basicInfoPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel10.setPreferredSize(new java.awt.Dimension(220, 215));
        jPanel10.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        patientBasicInfo.setMaximumSize(new java.awt.Dimension(250, 100));
        patientBasicInfo.setPreferredSize(new java.awt.Dimension(250, 100));
        patientBasicInfo.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jPanel7.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("First Name");
        jPanel7.add(jLabel1);
        jPanel7.add(filler7);

        jLabel2.setText("jLabel2");
        jPanel7.add(jLabel2);

        patientBasicInfo.add(jPanel7);

        jPanel11.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Last Name");
        jPanel11.add(jLabel3);
        jPanel11.add(filler8);

        jLabel4.setText("jLabel2");
        jPanel11.add(jLabel4);

        patientBasicInfo.add(jPanel11);

        jPanel12.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sex");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel12.add(jLabel5);
        jPanel12.add(filler1);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("jLabel2");
        jPanel12.add(jLabel6);

        patientBasicInfo.add(jPanel12);

        jPanel13.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Date of Birth");
        jPanel13.add(jLabel7);
        jPanel13.add(filler9);

        jLabel8.setText("jLabel2");
        jPanel13.add(jLabel8);

        patientBasicInfo.add(jPanel13);

        jPanel14.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Statement of Complaint");
        jPanel14.add(jLabel10);
        jPanel14.add(filler10);

        jLabel11.setText("jLabel2");
        jPanel14.add(jLabel11);

        patientBasicInfo.add(jPanel14);

        jPanel15.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Contact");
        jPanel15.add(jLabel12);
        jPanel15.add(filler11);

        jLabel13.setText("jLabel2");
        jPanel15.add(jLabel13);

        patientBasicInfo.add(jPanel15);

        jPanel10.add(patientBasicInfo);

        nokBasicInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Next Of Kin"));
        nokBasicInfo.setMaximumSize(new java.awt.Dimension(300, 100));
        nokBasicInfo.setPreferredSize(new java.awt.Dimension(180, 100));
        nokBasicInfo.setLayout(new java.awt.GridLayout(0, 1));

        jPanel17.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("First Name");
        jPanel17.add(jLabel14);
        jPanel17.add(filler12);

        jLabel15.setText("jLabel2");
        jPanel17.add(jLabel15);

        nokBasicInfo.add(jPanel17);

        jPanel18.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Last Name");
        jPanel18.add(jLabel16);
        jPanel18.add(filler13);

        jLabel17.setText("jLabel2");
        jPanel18.add(jLabel17);

        nokBasicInfo.add(jPanel18);

        jPanel19.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.LINE_AXIS));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Contact");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel19.add(jLabel18);
        jPanel19.add(filler3);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("jLabel2");
        jPanel19.add(jLabel19);

        nokBasicInfo.add(jPanel19);

        jPanel20.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Relatinship to Patient");
        jPanel20.add(jLabel20);
        jPanel20.add(filler14);

        jLabel21.setText("jLabel2");
        jPanel20.add(jLabel21);

        nokBasicInfo.add(jPanel20);

        jPanel10.add(nokBasicInfo);

        jPanel23.setMaximumSize(new java.awt.Dimension(32767, 100));

        jButton4.setText("Edit Basic Information");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel23.add(jButton4);

        jPanel10.add(jPanel23);

        basicInfoPanel.add(jPanel10);

        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.setMaximumSize(new java.awt.Dimension(32767, 100));

        jLabel22.setText("Extended information added:");
        jPanel6.add(jLabel22);

        jLabel23.setText("jLabel23");
        jPanel6.add(jLabel23);

        jPanel22.add(jPanel6);

        jButton1.setText("Add");
        jPanel21.add(jButton1);

        jButton2.setText("Edit Extended Information");
        jPanel21.add(jButton2);

        jPanel22.add(jPanel21);

        basicInfoPanel.add(jPanel22);

        jPanel5.add(basicInfoPanel);

        personalInfo.add(jPanel5);

        jTabbedPane1.addTab("Personal Info", personalInfo);

        setAppointmentPane.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Medical Info", setAppointmentPane);

        finances.setLayout(new java.awt.BorderLayout());

        jPanel25.setMaximumSize(new java.awt.Dimension(32767, 150));

        jLabel25.setText("Generate receipt");
        jPanel25.add(jLabel25);

        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel25.add(btnGenerate);

        finances.add(jPanel25, java.awt.BorderLayout.NORTH);

        jTabbedPane1.addTab("Finances", finances);

        patientViewPane.add(jTabbedPane1);

        getContentPane().add(patientViewPane, "patientView");

        reportsPane.setBackground(new java.awt.Color(204, 255, 204));
        reportsPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(reportsPane, "reports");

        jMenuBar.setBackground(new java.awt.Color(51, 204, 255));
        jMenuBar.setForeground(new java.awt.Color(51, 204, 255));
        jMenuBar.setMaximumSize(new java.awt.Dimension(94, 32769));
        jMenuBar.setPreferredSize(new java.awt.Dimension(94, 44));

        jMenu1.setBackground(new java.awt.Color(204, 255, 0));
        jMenu1.setText("Patient");

        miNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miNew.setText("New");
        miNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewActionPerformed(evt);
            }
        });
        jMenu1.add(miNew);

        miShowPatients.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miShowPatients.setText("Show All Patients");
        miShowPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miShowPatientsActionPerformed(evt);
            }
        });
        jMenu1.add(miShowPatients);

        jMenuBar.add(jMenu1);

        miReports.setText("Reports");
        miReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReportsActionPerformed(evt);
            }
        });

        miGenReports.setText("Generate");
        miGenReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGenReportsActionPerformed(evt);
            }
        });
        miReports.add(miGenReports);

        jMenuBar.add(miReports);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewActionPerformed
        // TODO add your handling code here:      
        NewPatientDialog dialog = new NewPatientDialog(this, true, null, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_miNewActionPerformed

    private void miShowPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miShowPatientsActionPerformed
        mainCardLayout.show(getContentPane(), "patientList");
    }//GEN-LAST:event_miShowPatientsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        JFrame receiptForAppointment = new JFrame();
        receiptForAppointment.setLocationRelativeTo(null);
        receiptForAppointment.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        receiptForAppointment.setSize(500, 600);
        receiptForAppointment.setLayout(new BorderLayout());
        receiptForAppointment.add(newAppointmentListComponent(currentPatient, (e) -> {
            receiptForAppointment.dispose();
            Receipt r = ReceiptController.generateReceipt(e.getModel());
            showReceiptWIndow(r, e.getModel().getDate(), true);
        }));
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void miReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReportsActionPerformed
        
    }//GEN-LAST:event_miReportsActionPerformed

    private void miGenReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGenReportsActionPerformed
        mainCardLayout.show(getContentPane(), "reports");
    }//GEN-LAST:event_miGenReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegularUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegularUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegularUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegularUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Utilities.setDefaultsForJFrame();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegularUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicInfoPanel;
    private javax.swing.JButton btnGenerate;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel finances;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem miGenReports;
    private javax.swing.JMenuItem miNew;
    private javax.swing.JMenu miReports;
    private javax.swing.JMenuItem miShowPatients;
    private javax.swing.JPanel nokBasicInfo;
    private javax.swing.JPanel patientBasicInfo;
    private javax.swing.JPanel patientListPane;
    private javax.swing.JPanel patientViewPane;
    private javax.swing.JPanel personalInfo;
    private javax.swing.JPanel reportsPane;
    private javax.swing.JPanel setAppointmentPane;
    // End of variables declaration//GEN-END:variables
    private CardLayout mainCardLayout;
    private Patient selectedPatientModel;

    private void initContent() {
        mainCardLayout = (CardLayout) getContentPane().getLayout();
        JMenu menuLogOut = new JMenu("Log Out");
        jMenuBar.add(Box.createHorizontalGlue());
        jMenuBar.add(menuLogOut);

        menuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogOutMouseClicked(evt);
            }

        });

        setExtendedState(JFrame.MAXIMIZED_BOTH);

        PatientController.addObserver(this);
    }

    private void menuLogOutMouseClicked(MouseEvent evt) {
        this.dispose();
        LoginScreen.start();
    }

    @Override
    public void update(Observable o, Object arg) {

    }

    private TableComponent<Appointment> newAppointmentListComponent(Patient currentPatient, TableEventListener<Appointment> tableListener) {
        List<Appointment> appointments = AppointmentsController.getAppointmentsForPatient(currentPatient.getId());

        TableComponent<Appointment> plc = new TableComponent<>(new AppointmentTableModel(appointments));
        plc.getTableModel().setFilterPredicate((p) -> p.getFormattedDate().equals(plc.getSearchExpression()));
        plc.setTableListener((TableEvent<Appointment> e) -> {
            tableListener.tableEventOccured(e);
        });
        return plc;
    }

    private void showViewPatient(Patient p) {
        JOptionPane.showMessageDialog(null, "Patient: " + p.getId() + " " + p.getName());
        selectedPatientModel = p;
        mainCardLayout.show(getContentPane(), "viewPatient");
    }

    private void initData() {
        patients = PatientController.getPatients();
        doctors = DoctorController.getAllDoctors();

        initPatientTable(patients);
        initGenerateReportsComponent();
    }

    private void initPatientTable(List<Patient> patients) {
        TableComponent<Patient> plc = new TableComponent<>(new PatientTableModel(patients));
        plc.getTableModel().setFilterPredicate((p) -> p.getName().toLowerCase().equals(plc.getSearchExpression().toLowerCase()));
        plc.setTableListener((TableEvent<Patient> e) -> {
            setCurrentPatient(e.getModel());
            mainCardLayout.next(getContentPane());
        });
        patientListPane.add(plc, BorderLayout.CENTER);
    }

    private void initReceiptTable(List<Receipt> receipts) {
        TableComponent<Receipt> rc = new TableComponent<>(new ReceiptTableModel(receipts));
        rc.getTableModel().setFilterPredicate((r) -> r.getReceiptNumber().toLowerCase().equals(rc.getSearchExpression().toLowerCase()));
        rc.setTableListener(e -> {
            showReceiptWIndow(e.getModel(), e.getModel().getDate(), false);
        });
        finances.add(rc, BorderLayout.CENTER);

    }

    private void showReceiptWIndow(Receipt receipt, LocalDate appointmentDate, Boolean setEditMode) {

        JFrame receiptFrame = new JFrame();
        receiptFrame.setLocationRelativeTo(null);
        receiptFrame.setSize(400, 600);
        receiptFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        receiptFrame.setLayout(new BorderLayout());
        ReceiptComponent rc = new ReceiptComponent(receipt, currentPatient, appointmentDate);
        receiptFrame.add(rc, BorderLayout.CENTER);
        if (setEditMode) {
            rc.setEditMode(ReceiptController.getAllPaymentMethods());
        }
        receiptFrame.setVisible(true);
    }

    private void setCurrentPatient(Patient model) {
        this.currentPatient = model;
        updateComponents();
    }

    private void updateComponents() {
        setAppointmentPane.removeAll();
        addAppointmentCalendarComponent();
        initReceiptTable(ReceiptController.getReceiptsforPatient(currentPatient.getId()));

    }

    private void addAppointmentCalendarComponent() {
        Doctor d = DoctorController.getDoctorForPatient(currentPatient.getId());
        List<Doctor> generalPhysicians = DoctorController.getGeneralPhysicians();

        AppointmentsPane appointmentsPane = new AppointmentsPane(currentPatient, d, null, generalPhysicians);
        appointmentsPane.setBtnAddAppointmentActionListener((e) -> {
            Appointment a = appointmentsPane.getAppointment();
            System.out.println(a);
            try {
                AppointmentsController.setAppointment(a);
                mainCardLayout.show(getContentPane(), "Home");
            } catch (InvalidModelException ex) {
                Logger.getLogger(Tets.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        CalendarComponent calendar = new CalendarComponent();
        calendar.setScheduledAppointments(AppointmentsController.getScheduledAppointments(d.getId()));
        calendar.setMinimumDate(LocalDate.now());

        appointmentsPane.setCurrentDoctorChangedListener((e) -> {
            Doctor targetDoctor = appointmentsPane.getCurrentDoctor();
            SwingUtilities.invokeLater(() -> {
                calendar.setScheduledAppointments(AppointmentsController.getScheduledAppointments(targetDoctor.getId()));
            });

        });

        calendar.setFreeAppointmentsActionListener((calendarEvent) -> {
            appointmentsPane.setAppointment(calendarEvent.getAppointment());
        });

        setAppointmentPane.add(appointmentsPane, BorderLayout.NORTH);
        setAppointmentPane.add(calendar, BorderLayout.CENTER);
    }

    private void initGenerateReportsComponent() {
        GenerateReportComponent generateReportComponent = new GenerateReportComponent();
        generateReportComponent.setBtnGenerateListener(e -> {
            showReportFrame(generateReportComponent.getSelectedDate(), generateReportComponent.getReportType());
        });
        reportsPane.add(generateReportComponent, BorderLayout.CENTER);
    }

    private void showReportFrame(LocalDate selectedDate, ReportType reportType) {
        JFrame frame = new JFrame();
        frame.setLocationRelativeTo(null);
        frame.setSize(400, 600);
        frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        frame.setLayout(new BorderLayout());

        switch (reportType) {
            case WEEKLY:
                GeneralReportComponent weeklyReport = new GeneralReportComponent(ReportsController.generateWeeklyReport(selectedDate));
                frame.add(weeklyReport, BorderLayout.CENTER);
                break;
            case MONTHLY:
                GeneralReportComponent monthlyReport = new GeneralReportComponent(ReportsController.generateMonthlyReport(selectedDate));
                frame.add(monthlyReport, BorderLayout.CENTER);

                break;
            default:
                DailyReportComponent dailyReport = new DailyReportComponent(ReportsController.generateDailyReport(selectedDate));
                frame.add(dailyReport, BorderLayout.CENTER);
        }

        frame.setVisible(true);
    }

}
