/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlahov.client;

import com.kvlahov.client.components.AppointmentsPane;
import com.kvlahov.client.components.CalendarComponent;
import com.kvlahov.client.components.DailyReportComponent;
import com.kvlahov.client.components.GeneralReportComponent;
import com.kvlahov.client.components.GenerateReportComponent;
import com.kvlahov.client.components.NewPatientDialog;
import com.kvlahov.client.components.ReceiptComponent;
import com.kvlahov.client.components.TableComponent;
import com.kvlahov.client.events.TableEvent;
import com.kvlahov.client.events.TableEventListener;
import com.kvlahov.client.global.Constants;
import com.kvlahov.client.tableModels.AppointmentTableModel;
import com.kvlahov.client.tableModels.PatientTableModel;
import com.kvlahov.client.tableModels.ReceiptTableModel;
import com.kvlahov.controller.AppointmentsController;
import com.kvlahov.controller.DoctorController;
import com.kvlahov.controller.PatientController;
import com.kvlahov.controller.ReceiptController;
import com.kvlahov.controller.ReportsController;
import com.kvlahov.exceptions.InvalidModelException;
import com.kvlahov.model.Appointment;
import com.kvlahov.model.Doctor;
import com.kvlahov.model.Patient;
import com.kvlahov.model.Receipt;
import com.kvlahov.model.enums.ReportType;
import com.kvlahov.utils.Utilities;
import com.sun.javafx.geom.transform.BaseTransform;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.Box;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author lordo
 */
public class RegularUI extends javax.swing.JFrame implements Gui, Observer {

    private List<Patient> patients;
    private List<Doctor> doctors;
    private Patient currentPatient;
    private List<Appointment> scheduledAppointments;

    public RegularUI() {
        initComponents();
        initContent();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        patientListPane = new javax.swing.JPanel();
        patientViewPane = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        personalInfo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        basicInfoPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        patientBasicInfo = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblFirstName = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblLastName = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblSex = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblDateOfBirth = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblComplaint = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblContact = new javax.swing.JLabel();
        nokBasicInfo = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblNokFirstName = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblNokLastName = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblNokContact = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lblRelationship = new javax.swing.JLabel();
        patientBasicInfo1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        cbAssign = new javax.swing.JCheckBox();
        ddlDoctors = new javax.swing.JComboBox();
        btnAssignDoctor = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        btnEditBasicInfo = new javax.swing.JButton();
        setAppointmentPane = new javax.swing.JPanel();
        finances = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        receiptsPane = new javax.swing.JPanel();
        reportsPane = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miNew = new javax.swing.JMenuItem();
        miShowPatients = new javax.swing.JMenuItem();
        miReports = new javax.swing.JMenu();
        miGenReports = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel9.setText("Home");
        jPanel4.add(jLabel9);

        getContentPane().add(jPanel4, "Home");

        patientListPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(patientListPane, "patientList");

        patientViewPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 10));
        patientViewPane.setLayout(new javax.swing.BoxLayout(patientViewPane, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        personalInfo.setLayout(new javax.swing.BoxLayout(personalInfo, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        basicInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic information"));
        basicInfoPanel.setLayout(new javax.swing.BoxLayout(basicInfoPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel10.setPreferredSize(new java.awt.Dimension(220, 215));
        jPanel10.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        patientBasicInfo.setMaximumSize(new java.awt.Dimension(250, 100));
        patientBasicInfo.setPreferredSize(new java.awt.Dimension(250, 100));
        patientBasicInfo.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jPanel7.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("First Name");
        jPanel7.add(jLabel1);
        jPanel7.add(filler7);

        lblFirstName.setText("jLabel2");
        jPanel7.add(lblFirstName);

        patientBasicInfo.add(jPanel7);

        jPanel11.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Last Name");
        jPanel11.add(jLabel3);
        jPanel11.add(filler8);

        lblLastName.setText("jLabel2");
        jPanel11.add(lblLastName);

        patientBasicInfo.add(jPanel11);

        jPanel12.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sex");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel12.add(jLabel5);
        jPanel12.add(filler1);

        lblSex.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSex.setText("jLabel2");
        jPanel12.add(lblSex);

        patientBasicInfo.add(jPanel12);

        jPanel13.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Date of Birth");
        jPanel13.add(jLabel7);
        jPanel13.add(filler9);

        lblDateOfBirth.setText("jLabel2");
        jPanel13.add(lblDateOfBirth);

        patientBasicInfo.add(jPanel13);

        jPanel14.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Statement of Complaint");
        jPanel14.add(jLabel10);
        jPanel14.add(filler10);

        lblComplaint.setText("jLabel2");
        jPanel14.add(lblComplaint);

        patientBasicInfo.add(jPanel14);

        jPanel15.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Contact");
        jPanel15.add(jLabel12);
        jPanel15.add(filler11);

        lblContact.setText("jLabel2");
        jPanel15.add(lblContact);

        patientBasicInfo.add(jPanel15);

        jPanel10.add(patientBasicInfo);

        nokBasicInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Next Of Kin"));
        nokBasicInfo.setMaximumSize(new java.awt.Dimension(300, 100));
        nokBasicInfo.setPreferredSize(new java.awt.Dimension(180, 100));
        nokBasicInfo.setLayout(new java.awt.GridLayout(0, 1));

        jPanel17.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("First Name");
        jPanel17.add(jLabel14);
        jPanel17.add(filler12);

        lblNokFirstName.setText("jLabel2");
        jPanel17.add(lblNokFirstName);

        nokBasicInfo.add(jPanel17);

        jPanel18.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.LINE_AXIS));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Last Name");
        jPanel18.add(jLabel16);
        jPanel18.add(filler13);

        lblNokLastName.setText("jLabel2");
        jPanel18.add(lblNokLastName);

        nokBasicInfo.add(jPanel18);

        jPanel19.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.LINE_AXIS));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Contact");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel19.add(jLabel18);
        jPanel19.add(filler3);

        lblNokContact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNokContact.setText("jLabel2");
        jPanel19.add(lblNokContact);

        nokBasicInfo.add(jPanel19);

        jPanel20.setMaximumSize(new java.awt.Dimension(150, 20));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.LINE_AXIS));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Relatinship to Patient");
        jPanel20.add(jLabel20);
        jPanel20.add(filler14);

        lblRelationship.setText("jLabel2");
        jPanel20.add(lblRelationship);

        nokBasicInfo.add(jPanel20);

        jPanel10.add(nokBasicInfo);

        patientBasicInfo1.setMaximumSize(new java.awt.Dimension(250, 100));
        patientBasicInfo1.setPreferredSize(new java.awt.Dimension(250, 100));
        patientBasicInfo1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Doctor");
        patientBasicInfo1.add(jLabel2);

        lblDoctor.setText("N/A");
        patientBasicInfo1.add(lblDoctor);

        cbAssign.setText("Assign Doctor");
        cbAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAssignActionPerformed(evt);
            }
        });
        patientBasicInfo1.add(cbAssign);

        ddlDoctors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        patientBasicInfo1.add(ddlDoctors);

        btnAssignDoctor.setText("Assign Doctor");
        btnAssignDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDoctorActionPerformed(evt);
            }
        });
        patientBasicInfo1.add(btnAssignDoctor);

        jPanel10.add(patientBasicInfo1);

        jPanel23.setMaximumSize(new java.awt.Dimension(32767, 100));

        btnEditBasicInfo.setText("Edit");
        btnEditBasicInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBasicInfoActionPerformed(evt);
            }
        });
        jPanel23.add(btnEditBasicInfo);

        jPanel10.add(jPanel23);

        basicInfoPanel.add(jPanel10);

        jPanel5.add(basicInfoPanel);

        personalInfo.add(jPanel5);

        jTabbedPane1.addTab("Personal Info", personalInfo);

        setAppointmentPane.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Medical Info", setAppointmentPane);

        finances.setLayout(new java.awt.BorderLayout());

        jPanel25.setMaximumSize(new java.awt.Dimension(32767, 150));

        jLabel25.setText("Generate receipt");
        jPanel25.add(jLabel25);

        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel25.add(btnGenerate);

        finances.add(jPanel25, java.awt.BorderLayout.NORTH);

        receiptsPane.setLayout(new java.awt.BorderLayout());
        finances.add(receiptsPane, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Finances", finances);

        patientViewPane.add(jTabbedPane1);

        getContentPane().add(patientViewPane, "patientView");

        reportsPane.setBackground(new java.awt.Color(204, 255, 204));
        reportsPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(reportsPane, "reports");

        jMenuBar.setBackground(new java.awt.Color(51, 204, 255));
        jMenuBar.setForeground(new java.awt.Color(51, 204, 255));
        jMenuBar.setMaximumSize(new java.awt.Dimension(94, 32769));
        jMenuBar.setPreferredSize(new java.awt.Dimension(94, 44));

        jMenu1.setBackground(new java.awt.Color(204, 255, 0));
        jMenu1.setText("Patient");

        miNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miNew.setText("New");
        miNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewActionPerformed(evt);
            }
        });
        jMenu1.add(miNew);

        miShowPatients.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miShowPatients.setText("Show All Patients");
        miShowPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miShowPatientsActionPerformed(evt);
            }
        });
        jMenu1.add(miShowPatients);

        jMenuBar.add(jMenu1);

        miReports.setText("Reports");
        miReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReportsActionPerformed(evt);
            }
        });

        miGenReports.setText("Generate");
        miGenReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGenReportsActionPerformed(evt);
            }
        });
        miReports.add(miGenReports);

        jMenuBar.add(miReports);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewActionPerformed
        // TODO add your handling code here:      
        NewPatientDialog dialog = new NewPatientDialog(this, true, null, null);
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                SwingUtilities.invokeLater(() -> {
                    initPatientTable(PatientController.getPatients());
                    patientListPane.revalidate();
                    patientListPane.repaint();
                });
            }
        });
        dialog.setVisible(true);
    }//GEN-LAST:event_miNewActionPerformed

    private void miShowPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miShowPatientsActionPerformed
        SwingUtilities.invokeLater(() -> {
            initPatientTable(PatientController.getPatients());
            mainCardLayout.show(getContentPane(), "patientList");
        });
    }//GEN-LAST:event_miShowPatientsActionPerformed

    private void btnEditBasicInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBasicInfoActionPerformed
        NewPatientDialog dialog = new NewPatientDialog(this, true, currentPatient, null);
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                SwingUtilities.invokeLater(() -> {
                    updateBasicInfo(PatientController.getBasicInfo(currentPatient.getId()));
                });
            }
        });
        dialog.setVisible(true);
    }//GEN-LAST:event_btnEditBasicInfoActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        SwingUtilities.invokeLater(() -> {
            JFrame receiptForAppointment = new JFrame();
            receiptForAppointment.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            receiptForAppointment.setPreferredSize(new Dimension(500, 600));
            receiptForAppointment.setSize(new Dimension(800, 800));
            receiptForAppointment.setLayout(new BorderLayout());
            receiptForAppointment.add(newAppointmentListComponent(currentPatient, (e) -> {
                SwingUtilities.invokeLater(() -> {
                    Receipt r = ReceiptController.generateReceipt(e.getModel());
                    showReceiptWIndow(r, e.getModel().getDate(), true);
                });
            }));

            receiptForAppointment.setLocationRelativeTo(null);
            receiptForAppointment.setVisible(true);
        });
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void miReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReportsActionPerformed

    }//GEN-LAST:event_miReportsActionPerformed

    private void miGenReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGenReportsActionPerformed
        mainCardLayout.show(getContentPane(), "reports");
    }//GEN-LAST:event_miGenReportsActionPerformed

    private void btnAssignDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDoctorActionPerformed
        if (!cbAssign.isSelected()) {
            return;
        }
        Doctor selectedDoctor = (Doctor) ddlDoctors.getSelectedItem();
        DoctorController.assignPatientToDoctor(currentPatient.getId(), selectedDoctor.getId());
        SwingUtilities.invokeLater(() -> {
            updateBasicInfo(currentPatient);
            addAppointmentCalendarComponent();
        });
    }//GEN-LAST:event_btnAssignDoctorActionPerformed

    private void cbAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAssignActionPerformed
        ddlDoctors.setEnabled(cbAssign.isSelected());
        btnAssignDoctor.setEnabled(cbAssign.isSelected());
    }//GEN-LAST:event_cbAssignActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegularUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegularUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegularUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegularUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Utilities.setDefaultsForJFrame();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegularUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicInfoPanel;
    private javax.swing.JButton btnAssignDoctor;
    private javax.swing.JButton btnEditBasicInfo;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JCheckBox cbAssign;
    private javax.swing.JComboBox ddlDoctors;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel finances;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblComplaint;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNokContact;
    private javax.swing.JLabel lblNokFirstName;
    private javax.swing.JLabel lblNokLastName;
    private javax.swing.JLabel lblRelationship;
    private javax.swing.JLabel lblSex;
    private javax.swing.JMenuItem miGenReports;
    private javax.swing.JMenuItem miNew;
    private javax.swing.JMenu miReports;
    private javax.swing.JMenuItem miShowPatients;
    private javax.swing.JPanel nokBasicInfo;
    private javax.swing.JPanel patientBasicInfo;
    private javax.swing.JPanel patientBasicInfo1;
    private javax.swing.JPanel patientListPane;
    private javax.swing.JPanel patientViewPane;
    private javax.swing.JPanel personalInfo;
    private javax.swing.JPanel receiptsPane;
    private javax.swing.JPanel reportsPane;
    private javax.swing.JPanel setAppointmentPane;
    // End of variables declaration//GEN-END:variables
    private CardLayout mainCardLayout;
    private Patient selectedPatientModel;

    private void initContent() {
        mainCardLayout = (CardLayout) getContentPane().getLayout();
        JMenu menuLogOut = new JMenu("Log Out");
        jMenuBar.add(Box.createHorizontalGlue());
        jMenuBar.add(menuLogOut);

        menuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogOutMouseClicked(evt);
            }

        });

        setExtendedState(JFrame.MAXIMIZED_BOTH);

        PatientController.addObserver(this);
    }

    private void menuLogOutMouseClicked(MouseEvent evt) {
        this.dispose();
        LoginScreen.start();
    }

    @Override
    public void update(Observable o, Object arg) {

    }

    private TableComponent<Appointment> newAppointmentListComponent(Patient currentPatient, TableEventListener<Appointment> tableListener) {
        List<Appointment> appointments = AppointmentsController.getAppointmentsForPatient(currentPatient.getId())
                .stream()
                .filter(a -> a.getStartTime().isBefore(LocalDateTime.now()))
                .collect(Collectors.toList());

        TableComponent<Appointment> plc = new TableComponent<>(new AppointmentTableModel(appointments));
        plc.getTableModel().setFilterPredicate((p) -> p.getFormattedDate().contains(plc.getSearchExpression()));
        plc.setTableListener((TableEvent<Appointment> e) -> {
            tableListener.tableEventOccured(e);
        });
        return plc;
    }

    private void showViewPatient(Patient p) {
        JOptionPane.showMessageDialog(null, "Patient: " + p.getId() + " " + p.getName());
        selectedPatientModel = p;
        mainCardLayout.show(getContentPane(), "viewPatient");
    }

    private void initData() {
        patients = PatientController.getPatients();
        doctors = DoctorController.getAllDoctors();

        ddlDoctors.setModel(new DefaultComboBoxModel(DoctorController.getGeneralPhysicians().toArray()));
        ddlDoctors.setEnabled(false);
        btnAssignDoctor.setEnabled(false);

//        initPatientTable(patients);
        initGenerateReportsComponent();
    }

    private void initPatientTable(List<Patient> patients) {
        patientListPane.removeAll();
        TableComponent<Patient> plc = new TableComponent<>(new PatientTableModel(patients));
        plc.getTableModel().setFilterPredicate((p) -> p.getName().toLowerCase().equals(plc.getSearchExpression().toLowerCase()));
        plc.setTableListener((TableEvent<Patient> e) -> {
            SwingUtilities.invokeLater(() -> {
                setCurrentPatient(e.getModel());
                mainCardLayout.next(getContentPane());
            });
        });
        patientListPane.add(plc, BorderLayout.CENTER);
    }

    private TableComponent<Receipt> receiptsTable;

    private void initReceiptTable(List<Receipt> receipts) {
        receiptsPane.removeAll();
        receiptsTable = new TableComponent<>(new ReceiptTableModel(receipts));
        receiptsTable.getTableModel().setFilterPredicate((r) -> r.getReceiptNumber().toLowerCase().contains(receiptsTable.getSearchExpression().toLowerCase()));
        receiptsTable.setTableListener(e -> {
            SwingUtilities.invokeLater(() -> {
                showReceiptWIndow(ReceiptController.getReceipt(e.getModel().getId()), e.getModel().getDate(), false);
            });
        });
        receiptsPane.add(receiptsTable, BorderLayout.CENTER);

    }

    private void showReceiptWIndow(Receipt receipt, LocalDate appointmentDate, Boolean setEditMode) {

        ReceiptFrame receiptFrame = new ReceiptFrame(receipt, setEditMode, currentPatient, appointmentDate);
        receiptFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                receiptsTable.getTableModel().updateModel(ReceiptController.getReceiptsforPatient(currentPatient.getId()));
            }
        });
        receiptFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        receiptFrame.setVisible(true);
    }

    private void setCurrentPatient(Patient model) {
        this.currentPatient = PatientController.getBasicInfo(model.getId());
        updateComponents();
    }

    private void updateComponents() {
        updateBasicInfo(currentPatient);
        SwingUtilities.invokeLater(() -> {
            setAppointmentPane.removeAll();
            addAppointmentCalendarComponent();
        });

        SwingUtilities.invokeLater(() -> {
            initReceiptTable(ReceiptController.getReceiptsforPatient(currentPatient.getId()));
        });

    }

    private void addAppointmentCalendarComponent() {
        setAppointmentPane.removeAll();
        Doctor d = DoctorController.getDoctorForPatient(currentPatient.getId());
        List<Doctor> generalPhysicians = DoctorController.getGeneralPhysicians();

        if (d == null) {
            return;
        }

        AppointmentsPane appointmentsPane = new AppointmentsPane(currentPatient, d, null, generalPhysicians);

        CalendarComponent calendar = new CalendarComponent();
        calendar.setScheduledAppointments(AppointmentsController.getScheduledAppointments(d.getId()));
        calendar.setMinimumDate(LocalDate.now());

        appointmentsPane.setBtnAddAppointmentActionListener((e) -> {
            SwingUtilities.invokeLater(() -> {
                Appointment a = appointmentsPane.getAppointment();
                try {
                    AppointmentsController.setAppointment(a);
                    calendar.setScheduledAppointments(AppointmentsController.getScheduledAppointments(d.getId()));
                    setAppointmentPane.revalidate();
                    setAppointmentPane.repaint();
                } catch (InvalidModelException ex) {
                    Logger.getLogger(Tets.class.getName()).log(Level.SEVERE, null, ex);
                }
            });
        });

        appointmentsPane.setCurrentDoctorChangedListener((e) -> {
            Doctor targetDoctor = appointmentsPane.getCurrentDoctor();
            SwingUtilities.invokeLater(() -> {
                calendar.setScheduledAppointments(AppointmentsController.getScheduledAppointments(targetDoctor.getId()));
            });

        });

        calendar.setFreeAppointmentsActionListener((calendarEvent) -> {
            appointmentsPane.setAppointment(calendarEvent.getAppointment());
        });

        setAppointmentPane.add(appointmentsPane, BorderLayout.NORTH);
        setAppointmentPane.add(calendar, BorderLayout.CENTER);
    }

    private void initGenerateReportsComponent() {
        GenerateReportComponent generateReportComponent = new GenerateReportComponent();
        generateReportComponent.setBtnGenerateListener(e -> {
            SwingUtilities.invokeLater(() -> {
                showReportFrame(generateReportComponent.getSelectedDate(), generateReportComponent.getReportType());
            });
        });
        reportsPane.add(generateReportComponent, BorderLayout.CENTER);
    }

    private void showReportFrame(LocalDate selectedDate, ReportType reportType) {
        JFrame frame = new JFrame();

        frame.setPreferredSize(new Dimension(800, 800));
        frame.setSize(new Dimension(800, 800));
        frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        frame.setLayout(new BorderLayout());
        frame.setLocationRelativeTo(null);

        switch (reportType) {
            case WEEKLY:
                GeneralReportComponent weeklyReport = new GeneralReportComponent(ReportsController.generateWeeklyReport(selectedDate));
                frame.add(weeklyReport, BorderLayout.CENTER);
                break;
            case MONTHLY:
                GeneralReportComponent monthlyReport = new GeneralReportComponent(ReportsController.generateMonthlyReport(selectedDate));
                frame.add(monthlyReport, BorderLayout.CENTER);

                break;
            default:
                DailyReportComponent dailyReport = new DailyReportComponent(ReportsController.generateDailyReport(selectedDate));
                frame.add(dailyReport, BorderLayout.CENTER);
        }

        frame.setVisible(true);
    }

    private void updateBasicInfo(Patient currentPatient) {
        lblFirstName.setText(currentPatient.getName());
        lblLastName.setText(currentPatient.getSurname());
        lblComplaint.setText(currentPatient.getStmtOfComplaint());
        lblContact.setText(currentPatient.getContact().getContact());
        lblDateOfBirth.setText(currentPatient.getDateOfBirth().format(Constants.DATE_FORMAT));
        lblNokContact.setText(currentPatient.getNextOfKin().getContactForBasicInformation().getContact());
        lblNokFirstName.setText(currentPatient.getNextOfKin().getName());
        lblNokLastName.setText(currentPatient.getNextOfKin().getSurname());
        lblRelationship.setText(currentPatient.getNextOfKin().getRelationshipToPatient());
        lblSex.setText(currentPatient.getSex().toString());

        SwingUtilities.invokeLater(() -> {
            Doctor doctorForPatient = DoctorController.getDoctorForPatient(currentPatient.getId());
            if (doctorForPatient != null) {
                lblDoctor.setText(doctorForPatient.toString());
            }
        });
    }

}
