/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlahov.client;

import com.kvlahov.client.components.Calendar;
import com.kvlahov.client.components.EditAppointment;
import com.kvlahov.controller.AppointmentsController;
import com.kvlahov.controller.DoctorController;
import com.kvlahov.controller.ServicesController;
import com.kvlahov.exceptions.InvalidModelException;
import com.kvlahov.model.Appointment;
import com.kvlahov.model.ServiceAppointment;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JPanel;

/**
 *
 * @author lordo
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    private List<ServiceAppointment> servicesForAppointment;

    public Test() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void initData() {
        Appointment appointment = AppointmentsController.getScheduledAppointments(4).get(0);
        EditAppointment pane = new EditAppointment(
                ServicesController.getTypesOfService(),
                appointment,
                ServicesController.getServices()
        );

        servicesForAppointment = ServicesController.getServicesForAppointment(appointment);
        pane.setServicesForAppointment(servicesForAppointment);

        pane.setBtnSaveActionListener((e) -> {
            try {
                AppointmentsController.updateAppointment(pane.getAppointment());
                List<ServiceAppointment> newServicesForAppointment = pane.getServicesForAppointment();

                ServicesController.addServicesForAppointment(newServicesForAppointment);
                ServicesController.deleteServicesForAppointment(servicesToDelete(newServicesForAppointment));
            } catch (InvalidModelException ex) {
                Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
            }

            pane.getServicesForAppointment().forEach(sa -> System.out.printf(
                    "\nID: %d\n ServiceID: %d\n Service: %s\n Quantity: %s\n Description: %s\n", sa.getId(), sa.getService().getId(), sa.getService().getType(), sa.getQuantity(), sa.getDescription()));
        });

        pane.setBtnCancelActionListener((e) -> {
            getContentPane().remove(pane);
        });

        add(pane);
    }

    private List<ServiceAppointment> servicesToDelete(List<ServiceAppointment> newServicesForAppointment) {
        //return every item from old list that is not in new list
        return servicesForAppointment
                .stream()
                .filter(sa -> !newServicesForAppointment.contains(sa))
                .collect(Collectors.toList());
    }
}
